export interface candidateProfileForm {
  application_number: { value: string },
  name: { value: string },
  father_name: { value: string },
  mother_name: { value: string },
  date_of_birth: { value: any },
  category: { value: string },
  email: { value: string },
  mobile_no: { value: string },
  gender: { value: string },
  nationality: { value: string },
  correspondance_address: { value: string },
  permanent_address: { value: string },
  state: { value: string },
  tenth_board: { value: string },
  tenth_marks: { value: string },
  tenth_passing_year: { value: string },
  twelveth_board: { value: string },
  twelveth_marks: { value: string },
  twelveth_passing_year: { value: string },
  tenth_certificate: { value: string },
  twelveth_certificate: { value: string },
  all_india_rank: { value: string },
  diploma_branch: { value: string },
  diploma_passing_year: { value: string },
  diploma_board: { value: string },
  diploma_institute: { value: string },
  diploma_marks: { value: string },
  diploma_certificate: { value: string },
  approved: boolean,
  submitted: boolean,
}

export interface CandidateProfileResponse {
  application_number: string,
  name: string,
  father_name: string,
  mother_name: string,
  date_of_birth: any,
  category: string,
  email: string,
  mobile_no: string,
  gender: string,
  nationality: string,
  correspondance_address: string,
  permanent_address: string,
  state: string,
  tenth_board: string,
  tenth_marks: string,
  tenth_passing_year: string,
  twelveth_board: string,
  twelveth_marks: string,
  twelveth_passing_year: string,
  tenth_certificate: string,
  twelveth_certificate: string,
  all_india_rank: string
  diploma_branch: string,
  diploma_passing_year: string,
  diploma_board: string,
  diploma_institute: string,
  diploma_marks: string,
  diploma_certificate: string,
  approved: boolean,
  submitted: boolean,
}