# Generated by Django 3.2.13 on 2022-12-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seat_management', '0002_auto_20221209_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='general_seat',
            new_name='general_seats',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='sc_seat',
            new_name='sc_seats',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='st_seat',
            new_name='st_seats',
        ),
    ]
