# Generated by Django 3.2.13 on 2022-12-10 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seat_management', '0004_allotment'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotment',
            name='allotment_category',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('scheduled_caste', 'Scheduled Caste'), ('schedule_tribe', 'Scheduled Tribe')], default='general', help_text='Category of allotment', max_length=255, null=True, verbose_name='Allotment Category'),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
