# Generated by Django 3.2.13 on 2022-12-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_profile', '0002_auto_20221209_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diploma_marks',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True, verbose_name='Marks in diploma'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tenth_marks',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True, verbose_name='Marks in tenth'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tweleveth_makrs',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True, verbose_name='Marks in twelveth'),
        ),
    ]
