# Generated by Django 3.2.13 on 2022-12-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_profile', '0003_auto_20221209_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
