# Generated by Django 3.2.13 on 2022-12-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_profile', '0005_alter_profile_prefrences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='prefrences',
        ),
    ]
