# Generated by Django 3.2.13 on 2022-12-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_profile', '0006_remove_profile_prefrences'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='all_india_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
