# Generated by Django 3.2.13 on 2022-12-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_profile', '0008_profile_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='application_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
