# Generated by Django 3.2.13 on 2022-12-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_profile', '0009_profile_application_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diploma_certificate',
            field=models.FileField(blank=True, null=True, upload_to='uploads/diploma_certificate/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tenth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='uploads/tenth_certificate/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tweleveth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='uploads/tweleveth_certificate/'),
        ),
    ]
