# Generated by Django 3.2.13 on 2022-12-16 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_profile', '0010_auto_20221217_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='permanenty_address',
            new_name='permanent_address',
        ),
    ]
