# Generated by Django 3.2.13 on 2022-12-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_profile', '0011_rename_permanenty_address_profile_permanent_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tweleveth_makrs',
            new_name='tweleveth_marks',
        ),
    ]
