# Generated by Django 3.2.13 on 2022-12-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_profile', '0012_rename_tweleveth_makrs_profile_tweleveth_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tweleveth_board',
            new_name='twelveth_board',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='tweleveth_marks',
            new_name='twelveth_marks',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='tweleveth_passing_year',
            new_name='twelveth_passing_year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tweleveth_certificate',
        ),
        migrations.AddField(
            model_name='profile',
            name='twelveth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='uploads/twelveth_certificate/'),
        ),
    ]
